const EditorEvent = {
    justifyCenter: "justifyCenter",   //中间对题
    justifyLeft: "justifyLeft",   //左对齐,
    justifyRight: "justifyRight",   //右对齐,
    indent: "indent",   //添加缩进,
    outdent: "outdent",   //去掉缩进,
    fontColor: "forecolor",   //value="red",//红色字体,
    fontSize: "fontsize",   //value="20px",//大标题,
    background: "backColor",   //value="green",//背景,
    fontWeightBold: "bold",   //加粗,
    textStyleUnderline: "underline",   //下划线,
    textStyleItalic: "italic",   //斜体,
    copy: "copy",   //复制,
    cut: "cut",   //剪切,
    paste: "paste",   //粘贴,
    selectAll: "selectAll",   //全选,
    delete: "delete",   //删除,
    forwardDelete: "forwarddelete",   //后删除,
    removeFormat: "removeFormat",   //清空格式,
    redo: "redo",   //前进一步,
    undo: "undo",   //后退一步,
    formatBlock: "formatblock",   //value="div",//插入div,
    insertHorizontalrule: "inserthorizontalrule",   //插入hr,
    insertOrderedlist: "insertorderedlist",   //插入ol,
    insertUnorderedlist: "insertunorderedlist",   //插入ul,
    insertCheckbox: "insertCheckbox",   //插入事项,
    enableObjectResizing: "enableObjectResizing",   //调整大小,
    textStyleStrikeThrough: "strikeThrough",   //删除线,
    insertImage: "insertimage",   //value="https://edu-image.nosdn.127.net/e798bf8a31c149179988cc28596ea2ba.jpg?imageView&quality=100&crop=0_5_6500_4793&thumbnail=33y33",//插入图像,
    createLink: "createlink",   //value="www.cnblogs.com/xiaohuochai",//增加链接,
    unLink: "unlink", //删除链接,
    editing: 'focused',
    notEditing: 'blur',
    save: 'save-note',
    selectionChange: 'selection-change'
};

export default EditorEvent;